language: php
sudo: false

php:
  - 7.3
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
- npm install
- ./node_modules/.bin/drakov --stealthmode -f "./*.apib" -p 3000&
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist

script:
- echo "Testing core suite"; vendor/bin/behat --suite=core;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/234214bec6e2c6e1c703
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
